version: 2.1

jobs:
  build:
    docker:
    - image: cimg/python:3.12
    - image: cimg/postgres:13.5-postgis
      environment:
        POSTGRES_USER: elephant
        POSTGRES_PASSWORD: localdev
        POSTGRES_DB: code
    - image: redis:6-alpine
    - image: localstack/localstack:3
      environment:
        SERVICES: s3,sqs,sns,sts,iam
        GATEWAY_LISTEN: 0.0.0.0:4576
    parallelism: 1
    resource_class: medium
    steps:
      - run:
          name: install Localstack CLI
          command: |
            python -m pip install --upgrade localstack
            localstack --version
      - run:
          name: install Localstack CLI
          command: |
            localstack wait -t 30 
